### ISSUE TITLE
moodle install fails

### ISSUE THREAD

**Issue by jvonau** [XSCE/xsce#203]
while using runansible: 

TASK: [moodle | Install moodle required packages] ***************************** 
changed: [127.0.0.1] => (item=moodle-xs,python-psycopg2)

TASK: [moodle | Remove stock moodle conf] ************************************* 
changed: [127.0.0.1]

TASK: [moodle | Configure moodle] ********************************************* 
changed: [127.0.0.1] => (item={'dest': '/etc/httpd/conf.d/020-xsce-moodle.conf', 'src': '020-xsce-moodle.conf.j2', 'mode': '0655'})
changed: [127.0.0.1] => (item={'dest': '/etc/systemd/system/moodle-xs.service', 'src': 'moodle-xs.service.j2', 'mode': '0655'})
changed: [127.0.0.1] => (item={'dest': '/usr/libexec/moodle-xs-init', 'src': 'moodle-xs-init', 'mode': '0755'})

TASK: [moodle | Create db user] *********************************************** 
changed: [127.0.0.1]

TASK: [moodle | Create database] ********************************************** 
failed: [127.0.0.1] => {"failed": true, "item": ""}
msg: Database query failed: encoding "UTF8" does not match locale "en_US"
DETAIL:  The chosen LC_CTYPE setting requires encoding "LATIN1".

FATAL: all hosts have already failed -- aborting

http://crohr.me/journal/2014/postgres-rails-the-chosen-lc-ctype-setting-requires-encoding-latin1.html

root@schoolserver xsce]# locale
LANG=en_US
LC_CTYPE="en_US"
LC_NUMERIC="en_US"
LC_TIME="en_US"
LC_COLLATE="en_US"
LC_MONETARY="en_US"
LC_MESSAGES="en_US"
LC_PAPER="en_US"
LC_NAME="en_US"
LC_ADDRESS="en_US"
LC_TELEPHONE="en_US"
LC_MEASUREMENT="en_US"
LC_IDENTIFICATION="en_US"

somebody else might hit this.

**Comment by tim-moody** [comment]
is this a problem with the install or a problem with moodle?  don’t think anything has changed for a long time and I’ve never seen this.
what’s the fix?
From: Jerry Vonau 
Sent: Sunday, February 01, 2015 7:35 PM
To: XSCE/xsce 
Subject: [xsce] moodle install fails (#203)

while using runansible: 

TASK: [moodle | Install moodle required packages] ***************************** 
changed: [127.0.0.1] => (item=moodle-xs,python-psycopg2)

TASK: [moodle | Remove stock moodle conf] ************************************* 
changed: [127.0.0.1]

TASK: [moodle | Configure moodle] ********************************************* 
changed: [127.0.0.1] => (item={'dest': '/etc/httpd/conf.d/020-xsce-moodle.conf', 'src': '020-xsce-moodle.conf.j2', 'mode': '0655'})
changed: [127.0.0.1] => (item={'dest': '/etc/systemd/system/moodle-xs.service', 'src': 'moodle-xs.service.j2', 'mode': '0655'})
changed: [127.0.0.1] => (item={'dest': '/usr/libexec/moodle-xs-init', 'src': 'moodle-xs-init', 'mode': '0755'})

TASK: [moodle | Create db user] *********************************************** 
changed: [127.0.0.1]

TASK: [moodle | Create database] ********************************************** 
failed: [127.0.0.1] => {"failed": true, "item": ""}
msg: Database query failed: encoding "UTF8" does not match locale "en_US"
DETAIL: The chosen LC_CTYPE setting requires encoding "LATIN1".

FATAL: all hosts have already failed -- aborting

http://crohr.me/journal/2014/postgres-rails-the-chosen-lc-ctype-setting-requires-encoding-latin1.html

root@schoolserver xsce]# locale
LANG=en_US
LC_CTYPE="en_US"
LC_NUMERIC="en_US"
LC_TIME="en_US"
LC_COLLATE="en_US"
LC_MONETARY="en_US"
LC_MESSAGES="en_US"
LC_PAPER="en_US"
LC_NAME="en_US"
LC_ADDRESS="en_US"
LC_TELEPHONE="en_US"
LC_MEASUREMENT="en_US"
LC_IDENTIFICATION="en_US"

somebody else might hit this.

**Comment by georgejhunt** [comment]
Jerry, are you installing on top of fc21? When I install on top of a
"netinst" fc21  iso, I'm forced to select locale during the "onfirstboot"
script.

Tim, are you still using fc20? Should we all agree to use fc21?

When I was first getting moodle to install, before ansible, I had to edit a
postgresql config file. When Santi rewrote my stuff, he got the postgresql
configured correctly. So I don't understand why this surfaces again. And I
did a full "runansible" late last week, without this failure.

**Comment by tim-moody** [comment]
I have run on fc21, but I typically test on fc20.

for fc21 I think I used the server role.

**Comment by tim-moody** [comment]
The locale on my f21 is

LANG=en_CA.UTF-8
LC_CTYPE="en_CA.UTF-8"
LC_NUMERIC="en_CA.UTF-8"
LC_TIME="en_CA.UTF-8"
LC_COLLATE="en_CA.UTF-8"
LC_MONETARY="en_CA.UTF-8"
LC_MESSAGES="en_CA.UTF-8"
LC_PAPER="en_CA.UTF-8"
LC_NAME="en_CA.UTF-8"
LC_ADDRESS="en_CA.UTF-8"
LC_TELEPHONE="en_CA.UTF-8"
LC_MEASUREMENT="en_CA.UTF-8"
LC_IDENTIFICATION="en_CA.UTF-8"
LC_ALL=

on f20 it’s

LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=

not sure why mine is what it is or why Jerry’s is different.

**Comment by jvonau** [comment]
Think this goes back to my original  anaconda install. I don't think we
should do anything as I'm I only one suffering. If someone else runs across
this we can look at this again. The cause is known but the fix is alluding
me at the moment.

**Comment by tim-moody** [comment]
I saw one suggestion to put LC_ALL=en_US.UTF-8 in /etc/environment
