### ISSUE TITLE
Ajenti fails on fedora 21

### ISSUE THREAD

**Issue by m-anish** [XSCE/xsce#236]
Below is the error log. This is a clean install on f21/Intel-NUC/x86_64
```
TASK: [ajenti | download ajenti from our repo] ******************************** 
failed: [127.0.0.1] => {"cmd": "/usr/bin/pip install --download-cache=/opt/schoolserver/pip-packages http://download.unleashkids.org/xsce/downloads/ajenti-0.99.34-patched5.tar.gz", "failed": true}
msg: stdout: Downloading/unpacking http://download.unleashkids.org/xsce/downloads/ajenti-0.99.34-patched5.tar.gz
  Storing download in cache at /opt/schoolserver/pip-packages/http%3A%2F%2Fdownload.unleashkids.org%2Fxsce%2Fdownloads%2Fajenti-0.99.34-patched5.tar.gz
  Running setup.py (path:/tmp/pip-4ViTps-build/setup.py) egg_info for package from http://download.unleashkids.org/xsce/downloads/ajenti-0.99.34-patched5.tar.gz
    
    warning: no previously-included files matching '*~' found under directory 'ajenti'
    warning: no previously-included files matching '*' found under directory 'packaging'
    warning: no previously-included files matching '*.*' found under directory 'packaging'
    warning: no files found matching 'COPYRIGHT'
    warning: no files found matching 'LICENSE'
    no previously-included directories found matching 'ajenti/plugins/elements'
    no previously-included directories found matching 'ajenti/plugins/ltfs'
    no previously-included directories found matching 'ajenti/plugins/test'
    no previously-included directories found matching 'ajenti/plugins/test*'
Requirement already satisfied (use --upgrade to upgrade): pyOpenSSL in /usr/lib64/python2.7/site-packages (from ajenti==0.99.34-patched5)
Requirement already satisfied (use --upgrade to upgrade): gevent in /usr/lib/python2.7/site-packages (from ajenti==0.99.34-patched5)
Downloading/unpacking gevent-socketio (from ajenti==0.99.34-patched5)
  Downloading gevent_socketio-0.3.6-py27-none-any.whl
  Storing download in cache at /opt/schoolserver/pip-packages/https%3A%2F%2Fpypi.python.org%2Fpackages%2F2.7%2Fg%2Fgevent-socketio%2Fgevent_socketio-0.3.6-py27-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): lxml>=2.2.4 in /usr/lib64/python2.7/site-packages (from ajenti==0.99.34-patched5)
Requirement already satisfied (use --upgrade to upgrade): python-daemon in /usr/lib/python2.7/site-packages (from ajenti==0.99.34-patched5)
Requirement already satisfied (use --upgrade to upgrade): passlib in /usr/lib/python2.7/site-packages (from ajenti==0.99.34-patched5)
Requirement already satisfied (use --upgrade to upgrade): psutil>=0.6.0 in /usr/lib64/python2.7/site-packages (from ajenti==0.99.34-patched5)
Downloading/unpacking requests (from ajenti==0.99.34-patched5)
  Storing download in cache at /opt/schoolserver/pip-packages/https%3A%2F%2Fpypi.python.org%2Fpackages%2Fpy2.py3%2Fr%2Frequests%2Frequests-2.5.3-py2.py3-none-any.whl
Downloading/unpacking reconfigure (from ajenti==0.99.34-patched5)
  Storing download in cache at /opt/schoolserver/pip-packages/https%3A%2F%2Fpypi.python.org%2Fpackages%2F2.7%2Fr%2Freconfigure%2Freconfigure-0.1.66-py2.py3-none-any.whl
Downloading/unpacking PIL (from ajenti==0.99.34-patched5)
  Could not find any downloads that satisfy the requirement PIL (from ajenti==0.99.34-patched5)
  Some externally hosted files were ignored (use --allow-external PIL to allow).
Cleaning up...
No distributions at all found for PIL (from ajenti==0.99.34-patched5)
Storing debug log for failure in /root/.pip/pip.log


FATAL: all hosts have already failed -- aborting
```

**Comment by tim-moody** [comment]
Yes, George mentioned this one; ajenti is broken on f21.  The easiest thing to do is put ajenti_install: False in /opt/schoolserver/xsce/vars/local_vars.yml



From: Anish Mangal 
Sent: Wednesday, March 11, 2015 8:38 AM
To: XSCE/xsce 
Subject: [xsce] Ajenti fails on fedora 21 (#236)

Below is the error log. This is a clean install on f21/Intel-NUC/x86_64

TASK: [ajenti | download ajenti from our repo] ******************************** 
failed: [127.0.0.1] => {"cmd": "/usr/bin/pip install --download-cache=/opt/schoolserver/pip-packages http://download.unleashkids.org/xsce/downloads/ajenti-0.99.34-patched5.tar.gz", "failed": true}
msg: stdout: Downloading/unpacking http://download.unleashkids.org/xsce/downloads/ajenti-0.99.34-patched5.tar.gz
  Storing download in cache at /opt/schoolserver/pip-packages/http%3A%2F%2Fdownload.unleashkids.org%2Fxsce%2Fdownloads%2Fajenti-0.99.34-patched5.tar.gz
  Running setup.py (path:/tmp/pip-4ViTps-build/setup.py) egg_info for package from http://download.unleashkids.org/xsce/downloads/ajenti-0.99.34-patched5.tar.gz

    warning: no previously-included files matching '*~' found under directory 'ajenti'
    warning: no previously-included files matching '*' found under directory 'packaging'
    warning: no previously-included files matching '*.*' found under directory 'packaging'
    warning: no files found matching 'COPYRIGHT'
    warning: no files found matching 'LICENSE'
    no previously-included directories found matching 'ajenti/plugins/elements'
    no previously-included directories found matching 'ajenti/plugins/ltfs'
    no previously-included directories found matching 'ajenti/plugins/test'
    no previously-included directories found matching 'ajenti/plugins/test*'
Requirement already satisfied (use --upgrade to upgrade): pyOpenSSL in /usr/lib64/python2.7/site-packages (from ajenti==0.99.34-patched5)
Requirement already satisfied (use --upgrade to upgrade): gevent in /usr/lib/python2.7/site-packages (from ajenti==0.99.34-patched5)
Downloading/unpacking gevent-socketio (from ajenti==0.99.34-patched5)
  Downloading gevent_socketio-0.3.6-py27-none-any.whl
  Storing download in cache at /opt/schoolserver/pip-packages/https%3A%2F%2Fpypi.python.org%2Fpackages%2F2.7%2Fg%2Fgevent-socketio%2Fgevent_socketio-0.3.6-py27-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): lxml>=2.2.4 in /usr/lib64/python2.7/site-packages (from ajenti==0.99.34-patched5)
Requirement already satisfied (use --upgrade to upgrade): python-daemon in /usr/lib/python2.7/site-packages (from ajenti==0.99.34-patched5)
Requirement already satisfied (use --upgrade to upgrade): passlib in /usr/lib/python2.7/site-packages (from ajenti==0.99.34-patched5)
Requirement already satisfied (use --upgrade to upgrade): psutil>=0.6.0 in /usr/lib64/python2.7/site-packages (from ajenti==0.99.34-patched5)
Downloading/unpacking requests (from ajenti==0.99.34-patched5)
  Storing download in cache at /opt/schoolserver/pip-packages/https%3A%2F%2Fpypi.python.org%2Fpackages%2Fpy2.py3%2Fr%2Frequests%2Frequests-2.5.3-py2.py3-none-any.whl
Downloading/unpacking reconfigure (from ajenti==0.99.34-patched5)
  Storing download in cache at /opt/schoolserver/pip-packages/https%3A%2F%2Fpypi.python.org%2Fpackages%2F2.7%2Fr%2Freconfigure%2Freconfigure-0.1.66-py2.py3-none-any.whl
Downloading/unpacking PIL (from ajenti==0.99.34-patched5)
  Could not find any downloads that satisfy the requirement PIL (from ajenti==0.99.34-patched5)
  Some externally hosted files were ignored (use --allow-external PIL to allow).
Cleaning up...
No distributions at all found for PIL (from ajenti==0.99.34-patched5)
Storing debug log for failure in /root/.pip/pip.log


FATAL: all hosts have already failed -- aborting

**Comment by m-anish** [comment]
I guess we don't install ajenti anymore, so we should close this?? as wontfix
