### ISSUE TITLE
Owncloud access forbidden (appliance install mode)

### ISSUE THREAD

**Issue by m-anish** [XSCE/xsce#237]
Hi, The owncloud access seems to be forbidden. Here is the sequence of steps

In appliance mode...
1. XSCE install (with owncloud enabled = false)
2. Rerun XSCE install (with owncloud enabled = true)
3. Go to <schoolserver_ip>/owncloud
4. Put in a username/password to do initial setup
    On this page, I get the additional warning:
    `Your data directory and your files are probably accessible from the internet. The .htaccess file that ownCloud provides is not working. We strongly suggest that you configure your webserver in a way that the data directory is no longer accessible or you move the data directory outside the webserver document root.`
5. After logging in, I get a `403 Forbidden: You don't have permission to access /owncloud/index.php/apps/files/ on this server.`

**Comment by tim-moody** [comment]
By XSCE Install do you mean runansible?

is the server available at http://schoolserver? http://schoolserver.lan?

what’s in /etc/httpd/conf.d/owncloud.conf?

what’s in /opt/owncloud/config/config.php?

owncloud is very fussy about protecting its data.  it has trusted domains and only allows access from those (schoolserver and schoolserver.lan should be in the list)

it does a url rewrite to the configuration url (schoolserver.lan) or if set up manually to the url on which you connected to the first screen

it also only allows access from certain ip addresses, which should be 172.18 ... or your wan subnet.  If this changes after installation, there could be a problem.


>From: Anish Mangal 
>Sent: Wednesday, March 11, 2015 9:49 AM
>To: XSCE/xsce 
>Subject: [xsce] Owncloud access forbidden (appliance install mode) (#237)
>
>Hi, The owncloud access seems to be forbidden. Here is the sequence of steps
>
>In appliance mode...
>1. XSCE install (with owncloud enabled = false)
>2. Rerun XSCE install (with owncloud enabled = true)
>3. Go to /owncloud
>4. Put in a username/password to do initial setup
>On this page, I get the additional warning:
>
>"Your data directory and your files are probably accessible from the internet. The .htaccess file that ownCloud provides is not working. We strongly suggest that you configure your webserver in a way that the data directory is no longer accessible or you move the data directory outside the webserver document root."
>
>I get a 403 Forbidden: You don't have permission to access /owncloud/index.php/apps/files/ on this server. 
>—

**Comment by tim-moody** [comment]
I just tried several experiments including removing the lines

'trusted_domains' =>
array (
  0 => 'schoolserver.lan',
  1 => 'schoolserver',
  2 => 'localhost',
  3 => '192.168.0.47',
),

from /opt/owncloud/config/config.php

now I can access owncloud from any ip

(3 => '192.168.0.47',  also worked, but now I have to hard code the server’s address for an appliance)

If lookup succeeds for 'schoolserver.lan' it should work as is.

We have taken the position that in appliance mode the server is wide open and assumed to be protected by something upstream, so if we follow that logic we could remove trusted domain.

in gateway mode this problem does not arise as schoolserver.lan is always resolvable (except on an android phone)

From: Anish Mangal 
Sent: Wednesday, March 11, 2015 9:49 AM
To: XSCE/xsce 
Subject: [xsce] Owncloud access forbidden (appliance install mode) (#237)

Hi, The owncloud access seems to be forbidden. Here is the sequence of steps

In appliance mode...
1. XSCE install (with owncloud enabled = false)
2. Rerun XSCE install (with owncloud enabled = true)
3. Go to /owncloud
4. Put in a username/password to do initial setup
On this page, I get the additional warning:

"Your data directory and your files are probably accessible from the internet. The .htaccess file that ownCloud provides is not working. We strongly suggest that you configure your webserver in a way that the data directory is no longer accessible or you move the data directory outside the webserver document root."
1.. I get a 403 Forbidden: You don't have permission to access /owncloud/index.php/apps/files/ on this server.
