### ISSUE TITLE
Substituting wifi adapter causes hostapd to fail

### ISSUE THREAD

**Issue by tim-moody** [XSCE/xsce#520]
if a new wifi adapter is connected to the server and the old one removed, the ifcfg-wlan0 file remains and the new adapter is not discovered.

**Comment by jvonau** [comment]
Can you clarify what you mean by discovered? kernel fails to populate
/sys/class/net? doesn't show up in "nmcli d"? before or after running
xsce-network? If it's after running xsce-network please attach the
xsce-network.log file to this issue please.

**Comment by tim-moody** [comment]
start with http://download.unleashkids.org/xsce/downloads/os/xo1.5/32023CE1_xo1.5_151128_base.img.zip

Rm /.olpc-configured
Reboot
Hostapd not working
ip addr show new wlan0 and br0, both down
Git pull
./xsce-network
TASK: [network | WiFi enslaving {{xsce_wireless_lan_iface}} to Bridge] ********
fatal: [127.0.0.1] => {'msg': "One or more undefined variables: 'dict object' has no attribute u'ansible_eth0\\nwlan0'", 'failed': True}
fatal: [127.0.0.1] => {'msg': "One or more undefined variables: 'dict object' has no attribute u'ansible_eth0\\nwlan0'", 'failed': True}

http://paste.fedoraproject.org/296321/89922581

10.8.0.22

**Comment by tim-moody** [comment]
btw, George fixed this on a previous install by running an older version of runtags network and then

iw dev wlan0 set 4addr on
brctl addif br0 wlan0
systemctl restart hostapd

but that did work in this case

**Comment by jvonau** [comment]
[cutoff.txt](https://github.com/XSCE/xsce/files/49010/cutoff.txt)
I've got it going farther along now, doesn't fail at TASK: [network | Wired enslaving] There should be no wired devices, got past that. stopped at I need the box rebooted. Thought it was a single wifi device that was being replaced, not 2 present. Your initial report of replacing usb AP left out the fact that this was an XO, we don't really support 2 wifi's on the LAN. back in a while should be do-able

**Comment by tim-moody** [comment]
yes, this is xo-1.5.  thought the image used to install would clarify that

there are not 2 wifi adapters on the lan as the internal one is not being used because it is unable to serve as an AP, so no need to support two at least for this case.

this is a stock target for xo-1.5 and 4 to serve as an AP

**Comment by jvonau** [comment]
Where was a "brctl addbr br0" that locked NM out in there somewhere. Pushed #521 with the fix
completed run: http://paste.fedoraproject.org/296472/14490159
