### ISSUE TITLE
new issue with xs-authserver?

### ISSUE THREAD

**Issue by jvonau** [XSCE/xsce#547]
anybody else seeing this?
```
TASK: [authserver | check pip is installed] *********************************** 
ok: [127.0.0.1]

TASK: [authserver | download xs-authserver from pypi] ************************* 
failed: [127.0.0.1] => {"cmd": "/bin/pip install --download /opt/schoolserver/pip-packages xs-authserver", "failed": true}
msg: stdout: You are using pip version 6.0.8, however version 7.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Collecting xs-authserver
  Using cached xs-authserver-0.1.7.tar.gz
  Saved /opt/schoolserver/pip-packages/xs-authserver-0.1.7.tar.gz
Collecting Flask>=0.10.1 (from xs-authserver)
  Could not find any downloads that satisfy the requirement Flask>=0.10.1 (from xs-authserver)
  No distributions at all found for Flask>=0.10.1 (from xs-authserver)


FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/root/xsce.retry

127.0.0.1                  : ok=45   changed=8    unreachable=0    failed=1   
```

**Comment by tim-moody** [comment]
Mischievous elves? Sent from my BlackBerry® PlayBook™www.blackberry.comFrom: "Jerry Vonau" <notifications@github.com>To: "XSCE/xsce" <xsce@noreply.github.com>Sent: 25 December, 2015 2:35 AMSubject: [xsce] new issue with xs-authserver? (#547)anybody else seeing this?

TASK: [authserver | check pip is installed] *********************************** 
ok: [127001]

TASK: [authserver | download xs-authserver from pypi] ************************* 
failed: [127001] => {"cmd": "/bin/pip install --download /opt/schoolserver/pip-packages xs-authserver", "failed": true}
msg: stdout: You are using pip version 608, however version 712 is available
You should consider upgrading via the 'pip install --upgrade pip' command
Collecting xs-authserver
  Using cached xs-authserver-017targz
  Saved /opt/schoolserver/pip-packages/xs-authserver-017targz
Collecting Flask>=0101 (from xs-authserver)
  Could not find any downloads that satisfy the requirement Flask>=0101 (from xs-authserver)
  No distributions at all found for Flask>=0101 (from xs-authserver)


FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/root/xsceretry

127001                  : ok=45   changed=8    unreachable=0    failed=1

**Comment by jvonau** [comment]
I'll go with that, seems transient, it's OK now.
