### ISSUE TITLE
Fedora updated ansisble to 2.0.1

### ISSUE THREAD

**Issue by jvonau** [XSCE/xsce#636]
dnf check-update ansible
dummy-config                                     12 kB/s | 1.6 kB     00:00  
xsce-testing                                    342 kB/s | 170 kB     00:00  
xsce-extra                                      337 kB/s | 128 kB     00:00  
Fedora 22 - x86_64 - Updates                    2.2 MB/s |  22 MB     00:10  
Last metadata expiration check performed 0:00:16 ago on Tue Apr 19 00:13:39 2016.
ansible.noarch                      2.0.1.0-2.fc22                       updates

Once installed, still works but I'm seeing different behavior now and warning abound

[DEPRECATION WARNING]: Instead of sudo/sudo_user, use become/become_user and 
make sure become_method is 'sudo' (default). This feature will be removed in a 
future release. Deprecation warnings can be disabled by setting 
deprecation_warnings=False in ansible.cfg.

[WARNING]: While constructing a mapping from
/opt/schoolserver/xsce/roles/authserver/tasks/main.yml, line 35, column 7, found
a duplicate dict key (mode).  Using last defined value only.

[WARNING]: Consider using get_url module rather than running wget

[DEPRECATION WARNING]: Using bare variables is deprecated. Update your playbooks
 so that the environment value uses the full variable syntax 
('{{wireless_list1.stdout_lines}}'). This feature will be removed in a future 
release. Deprecation warnings can be disabled by setting 
deprecation_warnings=False in ansible.cfg.

**Comment by jvonau** [comment]
https://docs.ansible.com/ansible/porting_guide_2.0.html

**Comment by jvonau** [comment]
https://bodhi.fedoraproject.org/updates/FEDORA-2016-bd36b17794

**Comment by jvonau** [comment]
PR #818 makes our code 2.1 compatible for use with F24+ where there is no ansibile1.9 available

**Comment by jvonau** [comment]
Tracking of build-systems in PR #828 for ansible2

**Comment by georgejhunt** [comment]
Our code now functions on >=2.2

**Comment by holta** [comment]
With the exception of Ansible 2.2.1 that did not work for Tim.

George has pinned/locked us to Ansible 2.2.0 for now, see #860

Hopefully 2.2.2 & 2.3.0 etc will be more smooth...
