### ISSUE TITLE
Button "Install Cofigured Options" fails

### ISSUE THREAD

**Issue by georgejhunt** [XSCE/xsce#853]
Initially I thought this bug was caused by the move from xsce to iiab repo.  But now it exists in our main repo also. Error message is:

PLAY [all] *********************************************************************

TASK [setup] *******************************************************************
fatal: [127.0.0.1]: FAILED! => {"failed": true, "msg": "failed to transfer file to ~/.ansible/tmp/ansible-tmp-1484874873.34-249709109845033/setup.py: [Errno 2] No such file or directory: '~/.ansible/tmp/ansible-tmp-1484874873.34-249709109845033/setup.py'"}
to retry, use: --limit @/opt/schoolserver/xsce/xsce-from-console.retry

PLAY RECAP *********************************************************************
127.0.0.1 : ok=0 changed=0 unreachable=0 failed=1 

Strange thing is that when I run the xsce-cmdsrv backend from a terminal, and then click the button, it does not fail. In the short term, the work around would be to click "Save Configuration" to create the setup file, and then to runansible from the command line. (just for developers who need to get on with it).

**Comment by tim-moody** [comment]
Ansible version?



Sent from my Samsung Galaxy smartphone.


-------- Original message --------

**Comment by georgejhunt** [comment]
On Thu, Jan 19, 2017 at 6:37 PM, Tim Moody <notifications@github.com> wrote:

> Ansible version?
>

Ansible --version = 2.2.1

**Comment by georgejhunt** [comment]
I did "pip uninstall ansible", and then "pip install ansible==2.1". 

The failure went away. 
As I remember, ansible was installing 2.2, and I did not encounter the failure. (yes 2.2 does also work)
So maybe we should change the "ansible" script to request a specific version.

**Comment by tim-moody** [comment]
Reno reported that the script installs 2.3.

**Comment by tim-moody** [comment]
I have the same issue with 2.2.1
