### ISSUE TITLE
runansible tests wrong value to determine OS

### ISSUE THREAD

**Issue by tim-moody** [XSCE/xsce#856]
# if vars/local_vars.yml is missing, put a default one in place
if [ ! -f ./vars/local_vars.yml ]; then
        OS=`grep ^ID= /etc/*release|cut -d= -f2`
        OS=${OS//\"/}
    if [ "$OS" = "Debian" ] || [ "$OS" = "raspbian" ]; then
                cp ./vars/debian.localvars ./vars/local_vars.yml
    else
                cp ./vars/centos.localvars ./vars/local_vars.yml
    fi
fi

OS is debian, not Debian
so tries to cp ./vars/centos.localvars which doesn't exist

**Comment by georgejhunt** [comment]
fixed in https://github.com/XSCE/xsce/commit/47290909421332fbfd0f9b9cf1193c6a794c941b
