### ISSUE TITLE
elgg does not install on vm with 8.6

### ISSUE THREAD

**Issue by tim-moody** [XSCE/xsce#857]
TASK [elgg : Expand it to our location] ****************************************
fatal: [127.0.0.1]: FAILED! => {"changed": false, "failed": true, "msg": "Unexpected error when accessing exploded file: [Errno 2] No such file or directory: '/opt/elgg-1.12.12/vendors/markdown/PHP Markdown Extra Readme.text'"}

**Comment by tim-moody** [comment]
looks like the directory name changed below

/opt/elgg-1.12.12/vendors/markdown

**Comment by holta** [comment]
Aside: a teacher's guide to Elgg is sorely needed, if TK Kang has made progress in the field with this?

Do we know his basic results, and if he's still focusing on Elgg?  (Not sure I can cc him from GitHub here?!)

**Comment by tim-moody** [comment]
looks like a know problem with unarchive in ansible

https://github.com/ansible/ansible-modules-core/issues/3706

**Comment by tim-moody** [comment]
https://fossies.org/linux/ansible/CHANGELOG.md claims fixed in 2.1.2

but I can unzip elgg1.12.12 manually with no errors

**Comment by tim-moody** [comment]
we use unarchive with tar files elsewhere.  think this is the only zip

**Comment by tim-moody** [comment]
see PR 863

**Comment by holta** [comment]
PR #863

Noting new here: am just testing GitHub's markdown syntax providing direct links to issues & pull requests, per "Issue references within a repository" @ https://guides.github.com/features/mastering-markdown/#GitHub-flavored-markdown

**Comment by georgejhunt** [comment]
PR #863 merged
