### ISSUE TITLE
ansible warnings text may cause problems for output parsing

### ISSUE THREAD

**Issue by tim-moody** [XSCE/xsce#858]
change settings to suppress output

**Comment by georgejhunt** [comment]
ansible/ansible.cfg changed to suppress warnings

**Comment by tim-moody** [comment]
Certain settings in Ansible are adjustable via a configuration file. The stock configuration should be sufficient for most users, but there may be reasons you would want to change them.

Changes can be made and used in a configuration file which will be processed in the following order:

* ANSIBLE_CONFIG (an environment variable)
* ansible.cfg (in the current directory)
* .ansible.cfg (in the home directory)
* /etc/ansible/ansible.cfg
Prior to 1.5 the order was:

* ansible.cfg (in the current directory)
* ANSIBLE_CONFIG (an environment variable)
* .ansible.cfg (in the home directory)
* /etc/ansible/ansible.cfg

**Comment by tim-moody** [comment]
on my docker vm /etc/ansible/ansible.cfg does not exist

**Comment by tim-moody** [comment]
maybe just put ansible.cfg in top of repo

**Comment by jvonau** [comment]
https://github.com/XSCE/xsce/commit/064591cd841e9cd850295c2c47436c5a36ec35fe
