### ISSUE TITLE
ansible 2.2.1 does not work

### ISSUE THREAD

**Issue by tim-moody** [XSCE/xsce#860]
change get-ansible script to get 2.2.0

**Comment by georgejhunt** [comment]
ansible script added. Pinned at version=2.2 in commit
https://github.com/XSCE/xsce/commit/7e973ad4a05b97e7107c3c0953396be736784888#diff-ac5f83218ea5f67914a930476e43f887R91

**Comment by jvonau** [comment]
https://github.com/iiab/iiab/pull/62
