### ISSUE TITLE
Default password warning for xsce-admin fails, but for pi succeeds

### ISSUE THREAD

**Issue by georgejhunt** [XSCE/xsce#867]
I've substituted .bashrc and .profile from /home/pi to /home/xsce-admin.

The /etc/profile does not seem to source *.sh in /etc/profiles.d/ for xsce-admin as it does for pi.

**Comment by georgejhunt** [comment]
This is failure occurs from remote ssh client. The LXDE warnings function as expected.

**Comment by georgejhunt** [comment]
symptoms still present. Logging on as root, or pi, via ssh issues a warning. But ssh logon to xsce-admin does not.
Maybe this is not a stopper for 6.2, since it is an enhacement rather than a bug

**Comment by tim-moody** [comment]
I wouldn't have included it.  So if it doesn't break the install, I'd leave it for now.

**Comment by georgejhunt** [comment]
understand and fix for 6.3
