### ISSUE TITLE
awstats still does not register schoolserver by default

### ISSUE THREAD

**Issue by georgejhunt** [XSCE/xsce#868]
It works if I put in the url: http://schoolserver.lan/awstats/awstats.pl?config=schoolserver.
But the link in utilities does not include the config clause.

I suppose we could just change the link on utils page. I don't expect folks to be accessing awstats via url directly.

**Comment by tim-moody** [comment]
agree


________________________________

**Comment by georgejhunt** [comment]
changed, pushed, function verified
