### ISSUE TITLE
on vm owncloud timed out

### ISSUE THREAD

**Issue by tim-moody** [XSCE/xsce#870]
jessie vm (vbox on ubuntu)

TASK [owncloud : Get the owncloud software] ************************************
fatal: [127.0.0.1]: FAILED! => {"changed": false, "failed": true, "msg": "async task did not complete within the requested time"}

**Comment by tim-moody** [comment]
ran it a second time in the same environment (vbox in ubuntu 16.4 on nuc) and didn't get this error

**Comment by georgejhunt** [comment]
I've had off and on difficulty with get_url.  And have substituted wget,
when I get failures.  Googling mentioned having to get it all into memory,
or in /tmp, as a shortcoming.

**Comment by tim-moody** [comment]
this happened again today
