### ISSUE TITLE
moodle gives 500 error

### ISSUE THREAD

**Issue by tim-moody** [XSCE/xsce#876]
on nuv http://192.168.0.33/moodle/ I get a 500 error

in the log 

[Thu Feb 02 11:04:02.490710 2017] [:error] [pid 28222] [client 192.168.0.56:65021] PHP Fatal error:  require_once(): Failed opening required 'config.php' (include_path='.:/usr/share/php:/usr/share/pear') in /opt/schoolserver/moodle/index.php on line 30
root@iiab-devel:/opt/schoolserver/iiab-menu# ll /opt/schoolserver/moodle/config.php
-rw-r----- 1 root root 695 Feb  1 10:58 /opt/schoolserver/moodle/config.php

config.php is owned by root

**Comment by tim-moody** [comment]
following https://docs.moodle.org/24/en/Security_recommendations I ran:

chmod -R 0755 /opt/schoolserver/moodle
find /opt/schoolserver/moodle  -type f -print -exec chmod 644 {} \;

now I get the error that schoolserver.lan is not resolved on the wan, but I think this means the permission problem is fixed.

**Comment by georgejhunt** [comment]
for some reason most of moodle is 644. But config.php is set 640. This
commit changes it
https://github.com/XSCE/xsce/commit/5ce60b3850add3647c2d7f2c25b21c7003caafd5

**Comment by tim-moody** [comment]
the directories are supposed to be 755. hopefully the elves will continue to set the other files to 644.

**Comment by tim-moody** [comment]
I suppose the authors feared 644 would allow anyone to read credentials in the config file.  The alternative would be to put the file in the www-data group and leave it 640.

**Comment by georgejhunt** [comment]
I do not know who is doing it. But someone keeps writing chown root:root,
after I have chgrp www-data on the whole moodle directory tree.

So until I understand who is the culprit, I'd prefer to chmod 644, which
appears to work, regardless of the potential security hole.  We can leave
this issue open, for further investigation.

**Comment by tim-moody** [comment]
agree. maybe moodle itself does it in which case yours is the only solution.
