### ISSUE TITLE
Delete Checked Files Button Broken

### ISSUE THREAD

**Issue by floydianslips** [XSCE/xsce#886]
The button under Install Content in the Admin Console seems to be dead. When files are checked and the button is pushed the boxes become unchecked at the files are still there.

**Comment by holta** [comment]
Confirmed, thx Josh!

http://box/admin -> Install Content -> Remove Downloaded Files -> Delete Checked Filed (blue button)

Tagging @tim-moody just so he's aware.

**Comment by tim-moody** [comment]
rm has full path for centos, but not for debian

**Comment by tim-moody** [comment]
there are more cases where the full path is used in xsce-cmdsrv but redhat and debian agree.
maybe they should be fixed as well.

**Comment by tim-moody** [comment]
for rm, removing full path works on debian
