### ISSUE TITLE
wordpress ownership still has apache on debian

### ISSUE THREAD

**Issue by tim-moody** [XSCE/xsce#902]
/library/wordpress

wp-config.php
wp-keys.php
wp-keys.php.BAK

are root:apache instead of root:www-data

**Comment by holta** [comment]
Thanks @tim-moody who fixed this on Raspbian on RPi3 too, as well as TK's Debian Mini PC (Zotac?)

"quick fix in /library/wordpress is
chown root:www-data wp-config.php
chown root:www-data wp-keys.php"

Or perhaps better more comprehensively below??

chown -R root:www-data /library/wordpress

**Comment by holta** [comment]
Backstory (incl error message & diagnostics) just in case something similar happens to others later...

WordPress was installed/enabled in an IIAB/XSCE 6.2 Release Candidate on Raspbian Pixel on RPi3 using http://box/admin -> Configure -> Check to Enable WordPress. -> Save Configuration -> Install Configured Options.

But http://box/wordpress came up completely blank when accessed via WAN, and showed "box is currently unable to handle this request. HTTP ERROR 500" when accessed via LAN (browsing from localhost or over the RPi3's internal WiFi).

Error Msg from /var/log/apache2/error.log was:

[Wed Apr 12 19:06:50.956028 2017] [:error] [pid 2242] [client 172.18.100.205:44833] PHP Warning:  require_once(/library/wordpress/wp-config.php): failed to open stream: Permission denied in /library/wordpress/wp-load.php on line 37
[Wed Apr 12 19:06:50.956213 2017] [:error] [pid 2242] [client 172.18.100.205:44833] PHP Fatal error:  require_once(): Failed opening required '/library/wordpress/wp-config.php' (include_path='.:/usr/share/php:/usr/share/pear') in /library/wordpress/wp-load.php on line 37

**Comment by jvonau** [comment]
fixed with #903 closing
